/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "baremetal/pkg/apis/baremetal/v1"
	scheme "baremetal/pkg/client/clientset/versioned/scheme"
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BareMetalJobsGetter has a method to return a BareMetalJobInterface.
// A group's client should implement this interface.
type BareMetalJobsGetter interface {
	BareMetalJobs(namespace string) BareMetalJobInterface
}

// BareMetalJobInterface has methods to work with BareMetalJob resources.
type BareMetalJobInterface interface {
	Create(ctx context.Context, bareMetalJob *v1.BareMetalJob, opts metav1.CreateOptions) (*v1.BareMetalJob, error)
	Update(ctx context.Context, bareMetalJob *v1.BareMetalJob, opts metav1.UpdateOptions) (*v1.BareMetalJob, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.BareMetalJob, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.BareMetalJobList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.BareMetalJob, err error)
	BareMetalJobExpansion
}

// bareMetalJobs implements BareMetalJobInterface
type bareMetalJobs struct {
	client rest.Interface
	ns     string
}

// newBareMetalJobs returns a BareMetalJobs
func newBareMetalJobs(c *MagellanV1Client, namespace string) *bareMetalJobs {
	return &bareMetalJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the bareMetalJob, and returns the corresponding bareMetalJob object, and an error if there is any.
func (c *bareMetalJobs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.BareMetalJob, err error) {
	result = &v1.BareMetalJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("baremetaljobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BareMetalJobs that match those selectors.
func (c *bareMetalJobs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.BareMetalJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.BareMetalJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("baremetaljobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested bareMetalJobs.
func (c *bareMetalJobs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("baremetaljobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a bareMetalJob and creates it.  Returns the server's representation of the bareMetalJob, and an error, if there is any.
func (c *bareMetalJobs) Create(ctx context.Context, bareMetalJob *v1.BareMetalJob, opts metav1.CreateOptions) (result *v1.BareMetalJob, err error) {
	result = &v1.BareMetalJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("baremetaljobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bareMetalJob).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a bareMetalJob and updates it. Returns the server's representation of the bareMetalJob, and an error, if there is any.
func (c *bareMetalJobs) Update(ctx context.Context, bareMetalJob *v1.BareMetalJob, opts metav1.UpdateOptions) (result *v1.BareMetalJob, err error) {
	result = &v1.BareMetalJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("baremetaljobs").
		Name(bareMetalJob.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bareMetalJob).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the bareMetalJob and deletes it. Returns an error if one occurs.
func (c *bareMetalJobs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("baremetaljobs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *bareMetalJobs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("baremetaljobs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched bareMetalJob.
func (c *bareMetalJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.BareMetalJob, err error) {
	result = &v1.BareMetalJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("baremetaljobs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
