/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	baremetalv1 "baremetal/pkg/apis/baremetal/v1"
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBareMetalJobs implements BareMetalJobInterface
type FakeBareMetalJobs struct {
	Fake *FakeMagellanV1
	ns   string
}

var baremetaljobsResource = schema.GroupVersionResource{Group: "magellan.baidu.com", Version: "v1", Resource: "baremetaljobs"}

var baremetaljobsKind = schema.GroupVersionKind{Group: "magellan.baidu.com", Version: "v1", Kind: "BareMetalJob"}

// Get takes name of the bareMetalJob, and returns the corresponding bareMetalJob object, and an error if there is any.
func (c *FakeBareMetalJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *baremetalv1.BareMetalJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(baremetaljobsResource, c.ns, name), &baremetalv1.BareMetalJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*baremetalv1.BareMetalJob), err
}

// List takes label and field selectors, and returns the list of BareMetalJobs that match those selectors.
func (c *FakeBareMetalJobs) List(ctx context.Context, opts v1.ListOptions) (result *baremetalv1.BareMetalJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(baremetaljobsResource, baremetaljobsKind, c.ns, opts), &baremetalv1.BareMetalJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &baremetalv1.BareMetalJobList{ListMeta: obj.(*baremetalv1.BareMetalJobList).ListMeta}
	for _, item := range obj.(*baremetalv1.BareMetalJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bareMetalJobs.
func (c *FakeBareMetalJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(baremetaljobsResource, c.ns, opts))

}

// Create takes the representation of a bareMetalJob and creates it.  Returns the server's representation of the bareMetalJob, and an error, if there is any.
func (c *FakeBareMetalJobs) Create(ctx context.Context, bareMetalJob *baremetalv1.BareMetalJob, opts v1.CreateOptions) (result *baremetalv1.BareMetalJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(baremetaljobsResource, c.ns, bareMetalJob), &baremetalv1.BareMetalJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*baremetalv1.BareMetalJob), err
}

// Update takes the representation of a bareMetalJob and updates it. Returns the server's representation of the bareMetalJob, and an error, if there is any.
func (c *FakeBareMetalJobs) Update(ctx context.Context, bareMetalJob *baremetalv1.BareMetalJob, opts v1.UpdateOptions) (result *baremetalv1.BareMetalJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(baremetaljobsResource, c.ns, bareMetalJob), &baremetalv1.BareMetalJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*baremetalv1.BareMetalJob), err
}

// Delete takes name of the bareMetalJob and deletes it. Returns an error if one occurs.
func (c *FakeBareMetalJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(baremetaljobsResource, c.ns, name), &baremetalv1.BareMetalJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBareMetalJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(baremetaljobsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &baremetalv1.BareMetalJobList{})
	return err
}

// Patch applies the patch and returns the patched bareMetalJob.
func (c *FakeBareMetalJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *baremetalv1.BareMetalJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(baremetaljobsResource, c.ns, name, pt, data, subresources...), &baremetalv1.BareMetalJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*baremetalv1.BareMetalJob), err
}
