apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: baremetaljobs.magellan.baidu.com
spec:
  group: magellan.baidu.com
  versions:
    - name: v1
      served: true
      storage: true
  version: v1
  scope: Namespaced
  names:
    plural: baremetaljobs
    singular: baremetaljob
    kind: BareMetalJob
    shortNames:
    - bmj